swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /account:
    put:
      tags:
        - account
      summary: Inserta busquedas por email
      x-swagger-router-controller: account.insert
      parameters:
        - name: parametros
          in: body
          required: true
          schema:
              $ref: '#/definitions/busqueda'
      responses:
        '200':
          description: devuelve las cuentas
    get:
      tags:
        - account
      summary: Obtiene busquedas por email
      x-swagger-router-controller: account.search
      parameters:
        - name: mail
          in: query
          required: true
          type: string
      responses:
        '200':
          description: devuelve las cuentas
    delete:
      tags:
        - account
      summary: elimina busqueda
      x-swagger-router-controller: account.remove
      parameters:
        - name: mail
          in: query
          required: true
          type: string
      responses:
        '200':
          description: retorna elemento eliminado

  /server/time:
    get:
      tags:
        - hours
      summary: the local server time
      x-swagger-router-controller: server.time
      responses:
        '200':
          description: the local server time answer

  /about:
    get:
      tags:
        - about
      summary: About this API
      x-swagger-router-controller: about.about
      parameters:
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: About
          schema:
            $ref: '#/definitions/about'


definitions:
  about:
    type: object
    properties:
      version:
        type: string
      name:
        type: string
  busqueda:
    type: object
    properties:
      mail:
        type: string
      zonaDestino:
        type: string
      fechaDesde:
        type: string
      fechaHasta:
        type: string
      adultos:
        type: number
